/*
  Selected indices are based on the id of the input rows. If filtered-out items
  are included in the 'selected' property, there will be a visual indication to
  the user of that fact.

  One may consider designing the parent component that provides the selection
  and filtering models to reset selections whenever a new filter is applied.
 */
import { RowId } from "../types";

/**
 * Specifies whether the user can select rows by clicking on a control in a
 * special column, by clicking on the row, or via either method.
 *
 * - column -- can only select by clicking on radio or checkbox input in special
 * column
 * - row -- selection column is hidden and selection can be done by clicking
 * anywhere in a row
 * - both -- selection can be done by either clicking on the input or row
 *
 * @public
 */
export type SelectMode = "column" | "row" | "both";

/**
 * Properties shared between {@link SingleSelectModel} and
 * {@link MultiSelectModel}.
 *
 * @public
 */
export interface BaseSelectModel {
  /**
   * The means of selecting rows available to the user.
   */
  mode: SelectMode;
  /**
   * The width of the select column. Set via CSS min-width and max-width
   * properties. The column is only shown if mode is set to "column".
   *
   * @defaultValue undefined - no CSS properties will be set
   */
  selectColWidth?: number;
}

/**
 * Properties specific to the {@link MultiSelectModel}.
 *
 * @public
 */
export interface MultiSelectState {
  /**
   * A type discriminator.
   */
  type: "multi";
  /**
   * The ids of the currently selected rows.
   */
  selected: RowId[];
  /**
   * Setter function for the selected ids.
   */
  setSelected: (selected: RowId[]) => void;
}

/**
 * Object to enable and configure the selection feature for a grid or table in
 * the multiselect mode.
 *
 * @public
 */
export type MultiSelectModel = BaseSelectModel & MultiSelectState;

/**
 * Properties specific to the {@link SingleSelectModel}.
 *
 * @public
 */
export interface SingleSelectState {
  /**
   * A type discriminator.
   */
  type: "single";
  /**
   * The id of the currently selected row, or null if none is selected.
   */
  selected: RowId | null;
  /**
   * Setter function for the "selected" property.
   */
  setSelected: (selected: RowId | null) => void;
  /**
   * String to uniquely identify the group of radio buttons.
   *
   * @remarks
   *
   * If specified, must be unique across all radio button groups on the web
   * page. Now optional because the
   * {@link https://react.dev/reference/react/useId | useId hook}
   * can be used to generate an ID.
   *
   * @defaultValue undefined - an id generated by the useId hook will be used
   */
  groupName?: string;
}

/**
 * Object to enable and configure the selection feature for a grid or table in
 * the single select mode.
 *
 * @public
 */
export type SingleSelectModel = BaseSelectModel & SingleSelectState;

/**
 * Object to enable and configure the selection feature for a grid or table.
 *
 * @public
 */
export type SelectModel = SingleSelectModel | MultiSelectModel;
